### ISSUE TITLE
Add option to add metadata to manifest

### ISSUE THREAD

**Issue by mnyrop** [mnyrop/wax_tasks#40]
Option for collection config to add metadata to iiif manifests , e.g.

```yml
collections:
  sample_collection:
    source: sample.json
    iiif:
      paged: true
      meta:
        label: title
        location: current_location
```
