### ISSUE TITLE
wax:lunr option to specify name of index file

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#82]
**Is your feature request related to a problem? Please describe.**
When using multilingual sites, you can't have different indexes by language.

**Describe the solution you'd like**
It could be interesting to have different search indexes and be able to specify one in the _config.yml file. For example : 
```YAML
lunr_index:
      content: false
      fields: [ tagname ]
      index_name: lunr-index-english.json
```

That would create a different lunr-index.json which could be used in a different lunr-ui.js and allow an english version of the website to only search and display results in english.

Could this be possible?
